### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 181968431** [Ostask/daodaoExcel#3]
在添加了合并后，再下面的单元格再添加合并，这时候，在上面的合并插入行，出现了问题，截图如下
https://github.com/181968431/img.git
我想可能是插入行的时候计算有点问题

**Comment by Ostask** [comment]
哇，居然真的有人用，我看看

**Comment by Ostask** [comment]
> 在添加了合并后，再下面的单元格再添加合并，这时候，在上面的合并插入行，出现了问题，截图如下
> https://github.com/181968431/img.git
> 我想可能是插入行的时候计算有点问题

大哥，要不加个微信，我看图没看出来哪有问题诶 d502724802
